<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Platforms\PostgreSQLPlatform;
use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260425130000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Creates refresh tokens table for JWT refresh cookie flow.';
    }

    public function up(Schema $schema): void
    {
        $this->abortIf(
            !$this->connection->getDatabasePlatform() instanceof PostgreSQLPlatform,
            'This migration can only be executed safely on PostgreSQL.',
        );

        $this->addSql(<<<'SQL'
CREATE TABLE refresh_tokens (
    id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    refresh_token VARCHAR(128) NOT NULL,
    username VARCHAR(255) NOT NULL,
    valid TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
    PRIMARY KEY(id),
    CONSTRAINT uniq_refresh_tokens_token UNIQUE (refresh_token)
)
SQL);
    }

    public function down(Schema $schema): void
    {
        $this->abortIf(
            !$this->connection->getDatabasePlatform() instanceof PostgreSQLPlatform,
            'This migration can only be executed safely on PostgreSQL.',
        );

        $this->addSql('DROP TABLE refresh_tokens');
    }
}
